version: v1
type: microservice
builder: npm
baseVersion: "1.0.0-alpha"
productionBranches: [ 'master']
artifactory:
  apiKey: vault:1o0
  username: vault:1
cd:
  couchdb: "true"
  profile: standard
  config:
    all:
      envVars:
        MY_VAR: 1
    production:
      envVars:
        Foo: 22
    branch:
      envVars:
        Bar: 'rofl'
  schedule: 'xxxxxx'
slackChannel: w3-rre
