version: v1
type: microservice
builder: npm
baseVersion: "1.0.0-alpha"
productionBranches: [ 'master']
cd:
  profile: multizoneClusterSystem
  config:
    all:
      envVars:
        MY_VAR: 1
    production:
      envVars:
        MY_VAR: 2
slackChannel: w3-rre